Ident c196 sign in with facebook
SparksNetwork/sparks-frontend pull request #116
Opened 2016-12-11 13:49 UTC by sdebaun

Manditory Checks
---

- [x] I added new tests for the issue I fixed or the feature I built
- [x] I ran `npm test` for the package I'm modifying
- [x] I used `npm run commit` instead of `git commit`

---

2016-12-11 13:49 UTC, sdebaun commented
![](https://github.trello.services/images/mini-trello-icon.png) [IDENT/UAT2: Connect with Facebook (create account)](https://trello.com/c/Z47xMHUS/196-ident-uat2-connect-with-facebook-create-account)

2016-12-12 16:34 UTC, TylorS requested changes

2016-12-12 16:34 UTC, TylorS commented on src/main/dash/index.ts
> +      ;
This semicolon should be brought back to line 17 for style consistency.

2016-12-12 18:05 UTC, TylorS approved these changes

2016-12-12 18:05 UTC, merged