Ident c185 use motorcycle router
SparksNetwork/sparks-frontend pull request #117
Opened 2016-12-11 14:15 UTC by sdebaun

Manditory Checks
---

- [x] I added new tests for the issue I fixed or the feature I built
- [ ] I ran `npm test` for the package I'm modifying
- [ ] I used `npm run commit` instead of `git commit`

---

2016-12-11 14:16 UTC, sdebaun commented
![](https://github.trello.services/images/mini-trello-icon.png) [REFACTOR: Drop-in replacement of our router with @motorcycle/router](https://trello.com/c/JKGZHkdq/185-refactor-drop-in-replacement-of-our-router-with-motorcycle-router)

2016-12-12 16:41 UTC, TylorS requested changes
I think that `Routing` should also be removed from the `app.ts` file then :+1:

2016-12-12 18:04 UTC, TylorS commented
Just need to fix the failing tests that have to do with unused imports

2016-12-12 18:23 UTC, TylorS approved these changes

2016-12-12 18:23 UTC, merged