Ident c202 real signin with facebook
SparksNetwork/sparks-frontend pull request #118
Opened 2016-12-11 14:56 UTC by sdebaun

Manditory Checks
---

- [x] I added new tests for the issue I fixed or the feature I built
- [x] I ran `npm test` for the package I'm modifying
- [x] I used `npm run commit` instead of `git commit`

---

2016-12-11 14:56 UTC, sdebaun commented
![](https://github.trello.services/images/mini-trello-icon.png) [IDENT/UAT6 Sign in with Facebook](https://trello.com/c/71ESZP87/202-ident-uat6-sign-in-with-facebook)

2016-12-11 20:14 UTC, sdebaun commented
![](https://github.trello.services/images/mini-trello-icon.png) [IDENT/UAT6 Sign in with Facebook](https://trello.com/c/71ESZP87/202-ident-uat6-sign-in-with-facebook)

2016-12-12 16:48 UTC, TylorS requested changes

2016-12-12 16:48 UTC, TylorS commented on src/main/dash/index.ts
> +      ;
Semicolon should be on line 17

2016-12-12 19:18 UTC, TylorS approved these changes

2016-12-12 19:25 UTC, merged